exemplo-web-master/asp.net Exemplo/ExermploMVC02/ExemploMVC02/ExemploMVC02/Models/Recrutadora.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ExemploMVC02.Models
{
    public class Recrutadora
    {
        [Required(ErrorMessage = "Nome não pode ser vazio")]
        [MinLength(7, ErrorMessage="Nome deve conter no minimo 7 caracteres")]
        [MaxLength(100, ErrorMessage= "Nome deve conter no maximo 100 caracteres")]

        public string Nome { get; set; }        
        
        public int Id { get; set; }
        [Required(ErrorMessage = "CPF não pode ser Vazio")]
        [MinLength(11, ErrorMessage = "CPF deve conter somente 11 caracteres")]
        public string CPF { get; set; }
        
        [Required(ErrorMessage="Tempo de empresa deve ser preenchido")]
        [Range(0, 6, ErrorMessage = "Pessoa deve ter entre 0 e 6 anos de empresa")]

        public byte TempoEmpresa { get; set; }
        
        [Required(ErrorMessage="Salário deve ser preenchido")]
        [Range(1200.00, 100000.00, ErrorMessage="Salário deve estar entre R$1.200 a R$ 100.000,00")]
        public decimal Salario { get; set; }
    }
}

exemplo-web-master/asp.net Exemplo/ExermploMVC02/ExemploMVC02/ExemploMVC02/Controllers/RecrutadoraController.cs
using ExemploMVC02.Models;
using ExemploMVC02.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExemploMVC02.Controllers
{
    public class RecrutadoraController : Controller
    {
        // GET: Recrutadora

        [HttpGet]
        public ActionResult Index()
        {
            List<Recrutadora> recrutadoras = new RecrutadoraRepositorio().ObterTodos();
            ViewBag.Recrutadoras = recrutadoras;
            ViewBag.TituloPagina = "Recrutadoras - Cadastro";
            return View();
        }

        [HttpGet]
        public ActionResult Cadastro()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Recrutadora recrutadora = new RecrutadoraRepositorio().ObterPeloId(id);
            ViewBag.Recrutadora = recrutadora;            
            return View();
        }


        [HttpPost]
        public ActionResult Store(Recrutadora recrutadora)
        {
            if (ModelState.IsValid)
            {
                int identificador = new RecrutadoraRepositorio().Cadastrar(recrutadora);
                return RedirectToAction("Editar", new { id = identificador }); 
            }

            ViewBag.recrutadora = recrutadora;
            return View("Cadastro");

           
        }
        public ActionResult Update(Recrutadora recrutadora)
        {
            bool alterado = new RecrutadoraRepositorio().Alterar(recrutadora);
            return null;
        }

        public ActionResult Excluir(int id)
        {
            bool apagado = new RecrutadoraRepositorio().Excluir(id);
            return null;
        }

        public ActionResult Buscar()
        {
            return View();
        }       
    }
}

exemplo-web-master/asp.net Exemplo/ExermploMVC02/ExemploMVC02/ExemploMVC02/Views/Recrutadora/Cadastro.cshtml
@{
    Layout = "~/Views/Shared/Master.cshtml";
}

<div cl>
    <div class="container border">
        <form action="/Recrutadora/Store" method="post" method="post" onsubmit="return false; validarFormulario()">
            <div class="form-group">
                <label for="campo-nome">Nome</label><span class="text-danger">*</span>
                <input type="text" class="form-control" name="Recrutadora.Nome" id="campo-nome" />
                @Html.ValidationMessage("Recrutadora.Nome", new {@class = "text-danger" })
            </div>
            <div class="form-group">
                <label for="campo-cpf">CPF</label>
                <input type="text" class="form-control" name="Recrutadora.CPF" id="campo-cpf" />
                @Html.ValidationMessage("Recrutadora.CPF", new {@class = "text-danger" })
            </div>
            <div class="form-group">
                <label for="campo-salario">Salário</label>
                <input type="number" class="form-control" name="Recrutadora.Salario" id="campo-salario" />
                @Html.ValidationMessage("Recrutadora.Salario", new {@class = "text-danger" })
            </div>
            <div>
                <label for="campo-tempo-empresa">Tempo de empresa</label>
                <select id="campo-tempo-empresa" name="Recrutadora.TempoEmpresa" class="custom-select">
                    <option value="0">Nunca trabalhou na empresa</option>
                    <option value="1">1 ano de empresa</option>
                    <option value="2">2 anos de empresa</option>
                    <option value="3">3 anos de empresa</option>
                    <option value="4">4 anos de empresa</option>
                    <option value="5">5 anos de empresa</option>
                    <option value="5">6 anos de empresa</option>
                </select>
                @Html.ValidationMessage("Rectutadora.Tempo-Empresa", new {@class = "text-danger" })
            </div>
            <div>
                <input type="reset" value="Limpar" class="btn btn-success" />

                <div class="row">
                    <div class="col-12  offset-5">
                        <button type="submit" class="btn btn-success">
                            SALVAR
                            <i class="fa fa-save"></i>
                        </button>
                    </div>
                </div>

            </div>
        </form>

    </div>
</div>

exemplo-web-master/asp.net Exemplo/ExermploMVC02/ExemploMVC02/ExemploMVC02/Views/Recrutadora/Editar.cshtml
@{
    Layout = "~/Views/Shared/Master.cshtml";
}




<div class="bg-warning">




<div>
    <h2>Cadastro de Recrutadora</h2>
</div>


<div">
    <div class="col-md-6 offset-3 bg-success">
        <form action="/Recrutadora/Update" method="post">
            <input type="hidden" name="recrutadora.Id" value="@ViewBag.Recrutadora.Id" />

            <div class="form-group">
                <label for="campo-nome">Nome</label>
                <input type="text" class="form-control" name="Recrutadora.Nome" id="campo-nome" value=@ViewBag.Recrutadora.Nome />
            </div>

            <div class="form-group">
                <label for="campo-cpf">CPF</label>
                <input type="text" class="form-control" name="Recrutadora.CPF" id="campo-cpf" value="@ViewBag.Recrutadora.CPF" />
            </div>

            <div class="form-group">
                <label for="campo-salario">Salário</label>
                <input type="text" class="form-control" name="Recrutadora.Salario" id="campo-salario" value="@ViewBag.Recrutadora.Salario" />
            </div>

            <div>
                <label for="campo-tempo-empresa">Tempo de empresa</label>
                <select id="campo-tempo-empresa" name="Recrutadora.TempoEmpresa">
                    @for (int i = 0; i < 7; i++)
                    {
                        if (i == @ViewBag.Recrutadora.TempoEmpresa)
                        {
                            <option value="@i" selected="selected">@i anos</option>
                        }
                        else
                        {
                            <option value="@i">@i anos</option>
                        }
                    }
                </select>
            </div>
            <div>
                <input type="reset" value="Limpar" />
                <input type="submit" value="Cadastrar" />
            </div>
        </form>
    </div>
</div>

exemplo-web-master/asp.net Exemplo/ExermploMVC02/ExemploMVC02/ExemploMVC02/Views/Recrutadora/Index.cshtml
@{
    Layout = "~/Views/Shared/Master.cshtml";
}
<!DOCTYPE html>
@Html.ActionLink("Nova recrutadora", "Cadastro", "Recrutadora", new { @class = "btn btn-primary float right mr-2" })

<h1>LISTA DE RECLUTADORAS</h1>

<div class="col-12 bg-danger">
    <div class="row">
        <div class="col-md-1">
            <button>CADASTAR</button>
        </div>

        <div class="col-md-3">
            <button>EDITAR</button>
        </div>

        <div class="col-md-5">
            <button>HOME</button>
        </div>

    </div>

</div>



<div class="mf-3 ml-3">
    <table class="table table-stripped table-hover">
        <thead>
            <tr class="bg-secondary text-white">
                <th>Código</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ExemploMVC02.Models.Recrutadora recrutadora in @ViewBag.Recrutadoras)
            {
                <tr>
                    <td>@recrutadora.Id</td>
                    <td>@recrutadora.Nome</td>
                    <td>@recrutadora.CPF</td>
                    <td>
                        <a href="/Recrutadora/Editar?id=@recrutadora.Id">
                            <i class="fa fa-pen-alt"></i>
                            Editar
                        </a>
                        <a href="/Recrutadora/Excluir?id=@recrutadora.Id">Excluir</a>
                        <i class="fa fa-trash"></i>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot class="bg-secondary text-white">
        <th>Código</th>
        <th>Nome</th>
        <th>CPF</th>
        <th>AÇÃO</th>
        </tfoot>
    </table>

</div>

exemplo-web-master/asp.net Exemplo/ExermploMVC02/ExemploMVC02/ExemploMVC02/Views/Shared/Master.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.TituloPagina</title>
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/all.css" />
    <script src="~/Content/bootstrap/js/bootstrap.js"></script>
    <script src="~/Scripts/Recrutadora/cadastro.js"></script>

</head>
<body>
    <div> 
        <div class="container-fluid">
            @RenderBody()
        </div>
    </div>
</body>
</html>